data:
    name: vessel_centerline_point
    data_dir: /mnt/maui/CTA_Coronary/project/xiongxs/Data
    train_path: 51_train_lightglue_L_new
    val_path: 51_val_lightglue_L_new
    train_size: 10000
    val_size: 200
    batch_size: 16
    num_workers: 8
    using_existing_list: True

model:
    name: vessel_pipeline
    extractor:
        name: gluefactory_nonfree.superpoint
        trainable: False
        sparse_outputs: True
    matcher:
        name: matchers.lightglue
        filter_threshold: 0.1
        flash: false
        checkpointed: true
        weights: /home/xiaosong_xiong/Intern_project/CTA2DSA/lightglue/LightGlue/pretrained_weight/superpoint_lightglue.pth

train:
    seed: 0
    epochs: 40
    log_every_iter: 100
    eval_every_iter: 500
    lr: 1e-4
    lr_schedule:
        start: 20
        type: exp
        on_epoch: true
        exp_div_10: 10
    plot: [5, 'gluefactory.visualization.visualize_batch.make_match_figures_dict']
benchmarks:
    hpatches:
      eval:
        estimator: opencv
        ransac_th: 0.5
